name: example
description: "This app shows an example of using the BirthChart widget."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  birth_chart:
    path: ../

flutter:
  uses-material-design: true
